Repository petpple/kiwi, pull requests merged in 2023-01, with the labels that each got.

#4 ⚡️ :: (#3) Sample page view 생성 및 폴더 구조 변경
  build.gradle
  src/main/java/com/petpple/kiwi/controller/AdminController.java
  src/main/java/com/petpple/kiwi/controller/UserController.java
  src/main/java/com/petpple/kiwi/domain/.gitkeep
  src/main/java/com/petpple/kiwi/repository/.gitkeep
  src/main/resources/application.properties
  src/main/webapp/WEB-INF/views/admin/adminMain.jsp
  src/main/webapp/WEB-INF/views/sample.jsp
  src/main/webapp/WEB-INF/views/user/userMain.jsp
  src/main/webapp/index.jsp
Labels: 기능 추가, 프로젝트 설정

#6 ⚡️ :: (#5) 폴더 구조 업데이트 - 보영
  src/main/java/com/petpple/kiwi/controller/Admin/.gitkeep
  src/main/java/com/petpple/kiwi/controller/Admin/AdminController.java
  src/main/java/com/petpple/kiwi/controller/Fsitter/.gitkeep
  src/main/java/com/petpple/kiwi/controller/Member/.gitkeep
  src/main/java/com/petpple/kiwi/controller/User/.gitkeep
  src/main/java/com/petpple/kiwi/controller/User/UserController.java
  src/main/java/com/petpple/kiwi/controller/Vsitter/.gitkeep
  src/main/webapp/WEB-INF/views/admin/.gitkeep
  src/main/webapp/WEB-INF/views/fsitter/.gitkeep
  src/main/webapp/WEB-INF/views/member/.gitkeep
  src/main/webapp/WEB-INF/views/user/.gitkeep
  src/main/webapp/WEB-INF/views/vsitter/.gitkeep
Labels: 프로젝트 설정

#8 ⚡️ :: (#7) 펫시터 샘플 페이지 업로드 -동현
  src/main/java/com/petpple/kiwi/controller/Admin/AdminController.java
  src/main/java/com/petpple/kiwi/controller/User/UserController.java
  src/main/webapp/WEB-INF/views/vsitter/css/pet_main.css
  src/main/webapp/WEB-INF/views/vsitter/img/profile.png
  src/main/webapp/WEB-INF/views/vsitter/svg/1.svg
  src/main/webapp/WEB-INF/views/vsitter/svg/2.svg
  src/main/webapp/WEB-INF/views/vsitter/svg/3.svg
  src/main/webapp/WEB-INF/views/vsitter/svg/4.svg
  src/main/webapp/WEB-INF/views/vsitter/vsitter_main.jsp
  src/main/webapp/WEB-INF/views/vsitter/vsitter_side.jsp
  src/main/webapp/WEB-INF/web.xml
Labels: 기능 추가

#14 📑 :: (#12) 의뢰인 펫시터 지원 프로세스 생성 - 소연
  src/main/java/com/petpple/kiwi/controller/Member/MemberController.java
  src/main/resources/static/images/member/hhh.svg
  src/main/resources/static/images/member/i.svg
  src/main/resources/static/images/member/t.svg
  src/main/resources/static/images/member/u.svg
  src/main/resources/static/images/member/y.svg
  src/main/webapp/WEB-INF/views/member/sitterAllowIn.jsp
  src/main/webapp/WEB-INF/views/member/sitterAllowOut.jsp
  src/main/webapp/WEB-INF/views/member/sitterAllowSubmit.jsp
  src/main/webapp/WEB-INF/views/member/sitterApply.jsp
  src/main/webapp/WEB-INF/views/member/sitterApplyForm.jsp
Labels: chore, 기능 추가

#16 ⚡️ :: (#10) vsitterMain 수정 -동현
  src/main/java/com/petpple/kiwi/controller/Vsitter/VsitterController.java
  src/main/resources/static/css/vsitter/petMain.css
  src/main/resources/static/images/vsitter/calendar.svg
  src/main/resources/static/images/vsitter/money.svg
  src/main/resources/static/images/vsitter/pet_info.svg
  src/main/resources/static/images/vsitter/sitting_on.svg
  src/main/resources/static/images/vsitter/timer-icon.svg
  src/main/resources/static/images/vsitter/u_svc.svg
  src/main/resources/static/images/vsitter/visit_svc.svg
  src/main/webapp/WEB-INF/views/vsitter/vsitterCal.jsp
  src/main/webapp/WEB-INF/views/vsitter/vsitterMain.jsp
  src/main/webapp/WEB-INF/views/vsitter/vsitterSide.jsp
Labels: 기능 추가

#18 📑 :: (#9) 유저 메인페이지 생성 - 현성
  src/main/java/com/petpple/kiwi/controller/User/UserController.java
  src/main/resources/static/css/user/userMain.css
  src/main/resources/static/images/user/dir.jpg
  src/main/resources/static/images/user/kiwi1.png
  src/main/resources/static/images/user/kiwi2.jpg
  src/main/resources/static/images/user/pet_sitting1.png
  src/main/resources/static/images/user/review1.png
  src/main/resources/static/images/user/review2.png
  src/main/resources/static/images/user/review3.png
  src/main/resources/static/images/user/service.jpg
  src/main/resources/static/images/user/suprise.jpg
  src/main/resources/static/images/user/캡처.PNG
  src/main/webapp/WEB-INF/views/user/userLoginForm.jsp
  src/main/webapp/WEB-INF/views/user/userMain.jsp
Labels: 기능 추가

#20 📑 :: (#11) 펫시터 마이페이지 생성 - 영관
  src/main/java/com/petpple/kiwi/controller/Fsitter/FsitterController.java
  src/main/resources/static/css/fsitter/fsitterMy.css
  src/main/resources/static/images/fsitter/1.svg
  src/main/resources/static/images/fsitter/2.svg
  src/main/resources/static/images/fsitter/h1.svg
  src/main/resources/static/images/fsitter/h2.svg
  src/main/resources/static/images/fsitter/h3.svg
  src/main/resources/static/images/fsitter/h4.svg
  src/main/resources/static/images/fsitter/logo1.png
  src/main/webapp/WEB-INF/views/fsitter/fsitterHeader.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyBank.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyBlock.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyDrawl.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyProfile.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterSide.jsp
Labels: 기능 추가

#22 📑 :: (#13) adminSide 생성 - 보영
  src/main/java/com/petpple/kiwi/controller/Admin/AdminController.java
  src/main/resources/static/css/admin/adminSide.css
  src/main/resources/static/css/main.css
  src/main/resources/static/javascript/admin/adminSide.js
  src/main/webapp/WEB-INF/views/admin/adminMain.jsp
  src/main/webapp/WEB-INF/views/admin/adminSide.jsp
Labels: 기능 추가

#26 ⚡️ :: (#17) 펫시터 일지 생성
  src/main/java/com/petpple/kiwi/controller/Vsitter/VsitterController.java
  src/main/resources/static/css/vsitter/petMain.css
  src/main/resources/static/images/vsitter/diary.svg
  src/main/webapp/WEB-INF/views/vsitter/vsitterCal.jsp
  src/main/webapp/WEB-INF/views/vsitter/vsitterDiaryForm.jsp
  src/main/webapp/WEB-INF/views/vsitter/vsitterDiaryPetChoice.jsp
  src/main/webapp/WEB-INF/views/vsitter/vsitterDiaryWritten.jsp
  src/main/webapp/WEB-INF/views/vsitter/vsitterMain.jsp
  src/main/webapp/WEB-INF/views/vsitter/vsitterSide.jsp
Labels: 기능 추가

#30 📑 :: (#28)펫시터 디렉터리 구조 및 파일 변경 -동현
  src/main/java/com/petpple/kiwi/controller/Fsitter/FsitterController.java
  src/main/java/com/petpple/kiwi/controller/Sitter/SitterController.java
  src/main/resources/static/css/sitter/petMain.css
  src/main/resources/static/css/sitter/sitterCal.css
  src/main/resources/static/css/sitter/sitterDiary.css
  src/main/resources/static/css/sitter/sitterMain.css
  src/main/resources/static/css/sitter/sitterMy.css
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyBlock.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyInfo.jsp
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyProfile.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterCal.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterDiaryForm.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterDiaryPetChoice.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterDiaryWritten.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterMain.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterMyBank.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterMyDrawl.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterMySide.jsp
  src/main/webapp/WEB-INF/views/vsitter/vsitterSide.jsp
Labels: chore

#33 📑 :: (#19) 유저 로그인 페이지 생성 - 현성
  src/main/java/com/petpple/kiwi/controller/User/UserController.java
  src/main/resources/static/css/user/uMain.css
  src/main/resources/static/css/user/userContract.css
  src/main/resources/static/css/user/userLoginForm.css
  src/main/resources/static/css/user/userMain.css
  src/main/webapp/WEB-INF/views/user/userContract.jsp
  src/main/webapp/WEB-INF/views/user/userLoginForm.jsp
  src/main/webapp/WEB-INF/views/user/userMain.jsp
Labels: 기능 추가

#39 📑 :: (#36) 의뢰인 메인페이지 생성(수정필요) - 소연
  src/main/java/com/petpple/kiwi/controller/Member/MemberController.java
  src/main/resources/static/css/member/memberMainPage.css
  src/main/resources/static/images/member/calendar.svg
  src/main/resources/static/images/member/pet_info.svg
  src/main/resources/static/images/member/profile.svg
  src/main/resources/static/images/member/sitting_on.svg
  src/main/resources/static/images/member/u_svc.svg
  src/main/resources/static/images/member/visit_svc.svg
  src/main/webapp/WEB-INF/views/member/memberCal.jsp
  src/main/webapp/WEB-INF/views/member/memberMain.jsp
  src/main/webapp/WEB-INF/views/member/memberSide.jsp
Labels: 기능 추가

#41 ⚡️ :: (#40) member 폴더 생성 후 분리
  src/main/java/com/petpple/kiwi/controller/Member/MemberController.java
  src/main/webapp/WEB-INF/views/member/form/memberApplyForm.jsp
  src/main/webapp/WEB-INF/views/member/form/vsitterApplyForm.jsp
  src/main/webapp/WEB-INF/views/member/mainPage/memberCal.jsp
  src/main/webapp/WEB-INF/views/member/mainPage/memberMain.jsp
  src/main/webapp/WEB-INF/views/member/mainPage/memberSide.jsp
  src/main/webapp/WEB-INF/views/member/myPage/memberMyInfo.jsp
  src/main/webapp/WEB-INF/views/member/review/memberReview.jsp
  src/main/webapp/WEB-INF/views/member/review/memberReviewT.jsp
  src/main/webapp/WEB-INF/views/member/sitterApply/memberApply.jsp
  src/main/webapp/WEB-INF/views/member/sitterApply/sitterAllowSubmit.jsp
  src/main/webapp/WEB-INF/views/member/sitterInOrOut/sitterAllowIn.jsp
  src/main/webapp/WEB-INF/views/member/sitterInOrOut/sitterAllowOut.jsp
Labels: chore, 기능 추가

#45 📑 :: (#34) 푸터 생성 - 현성
  src/main/java/com/petpple/kiwi/controller/User/UserController.java
  src/main/resources/static/css/user/FAQ.css
  src/main/resources/static/css/user/footer.css
  src/main/resources/static/css/user/userLoginForm.css
  src/main/resources/static/images/user/github1.png
  src/main/resources/static/images/user/github2.png
  src/main/resources/static/images/user/logo.png
  src/main/webapp/WEB-INF/views/user/footer.jsp
  src/main/webapp/WEB-INF/views/user/userFAQ.jsp
  src/main/webapp/WEB-INF/views/user/userMain.jsp
Labels: 기능 추가

#47 📑 :: (#44) 펫시터 마이펫 관리 - 영관
  src/main/java/com/petpple/kiwi/controller/Fsitter/FsitterController.java
  src/main/webapp/WEB-INF/views/fsitter/fsitterMyPet.jsp
Labels: 기능 추가

#48 ⚡️ :: (#31) 펫시터 일지 페이지 수정 및 메인 페이지 수정 -동현
  src/main/resources/static/css/sitter/rSlider.min.css
  src/main/resources/static/css/sitter/sitterDiary.css
  src/main/resources/static/css/sitter/sitterMain.css
  src/main/webapp/WEB-INF/views/sitter/rSlider.min.js
  src/main/webapp/WEB-INF/views/sitter/sitterDiaryForm.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterDiaryPetChoice.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterDiaryWritten.jsp
  src/main/webapp/WEB-INF/views/sitter/sitterMain.jsp
Labels: 기능 추가

#50 ⚡️ :: (#49) 유저 컨트롤러 수정 및 매핑 에러 해결-동현
  src/main/java/com/petpple/kiwi/controller/Sitter/SitterController.java
  src/main/java/com/petpple/kiwi/controller/User/UserController.java
  src/main/java/com/petpple/kiwi/controller/Vsitter/VsitterController.java
  src/main/webapp/WEB-INF/views/vsitter/vsitterSide.jsp
Labels: chore
